# Generated by Django 3.2.9 on 2021-12-30 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_person_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='username',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
